language: node_js
sudo: false
env:
   global:
   - secure: en+zpjwZaPFMVO6M0ilOIOVehlbCKiQeZq2yV9nS02xjgia2fDPTAirrqhUIZ9jwxdVofTGINpcKWChxd+N1UvmE9LHaMpeBly9CriPA8W64Q4ahY8PtzmPoXpy1fYHwT6IBe6q3z6WSZt9rgCSYJjwFTZ8ocfT2i8RrPlWjJMA=
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
node_js:
   - "0.12"
   - "0.10"
notifications:
   irc:
      channels: "chat.freenode.net#laxarjs"
      template: "%{repository_slug} (%{commit}) [%{branch}]: %{message}"
